import { Center, Text3D } from '@react-three/drei';
import { Canvas, useFrame, ThreeElements, useThree } from '@react-three/fiber';
import Head from 'next/head';
import { useLayoutEffect, useRef } from 'react';

const Scene = (props: ThreeElements['mesh']) => {
  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
  const mesh = useRef<any>(null!);

  useFrame((state, delta) => (mesh.current.rotation.z -= delta));

  const gl = useThree((state) => state.gl);

  useLayoutEffect(() => gl.setPixelRatio(0.1));

  return (
    <Center ref={mesh}>
      <Text3D font={'font/pressStart2P.json'} letterSpacing={-0.2} {...props}>
        <meshNormalMaterial />
        &lt;3
      </Text3D>
    </Center>
  );
};

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta content="Generated by create next app" name="description" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link href="/favicon.ico" rel="icon" />
    </Head>
    <div className="container flex h-screen items-center">
      <div className="h-[80%] w-full bg-gray">
        <Canvas gl={{ antialias: false }}>
          <Scene position={[0, 0, 0]} scale={2} />
        </Canvas>
      </div>
    </div>
  </>
);

// eslint-disable-next-line import/no-default-export
export default Home;
