import Head from 'next/head';

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta content="Generated by create next app" name="description" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link href="/favicon.ico" rel="icon" />
    </Head>
    <div className="container text-red-500">
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
    </div>
  </>
);

// eslint-disable-next-line import/no-default-export
export default Home;
