import { Center, Edges, Text3D } from '@react-three/drei';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import Head from 'next/head';
import { useLayoutEffect, useRef } from 'react';

const Scene = () => {
  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
  const mesh = useRef<any>(null!);

  const factor = 0.25;

  useFrame((state, delta) => (mesh.current.rotation.z -= delta * factor));
  useFrame((state, delta) => (mesh.current.rotation.x += delta * factor));
  useFrame((state, delta) => (mesh.current.rotation.z -= delta * factor));

  const gl = useThree((state) => state.gl);

  useLayoutEffect(() => gl.setPixelRatio(0.2));

  return (
    <Center position={[0, 0, -100]} ref={mesh} scale={50}>
      <Text3D font={'font/pressStart2P.json'} letterSpacing={-0.2}>
        <meshNormalMaterial />
        &lt;3
        <Edges />
      </Text3D>
    </Center>
  );
};

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta content="Generated by create next app" name="description" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link href="/favicon.ico" rel="icon" />
    </Head>
    <div className="container flex h-screen items-center">
      <div className="h-[80%] w-full bg-gray">
        <Canvas gl={{ antialias: false }}>
          <Scene />
        </Canvas>
      </div>
    </div>
  </>
);

// eslint-disable-next-line import/no-default-export
export default Home;
