# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
          cache: 'yarn'
      - run: yarn
      - name: Add .env.local file
        run: |
          touch ./.env.local
          echo GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_ENDPOINT }} >> ./.env.local
          echo NEXT_PUBLIC_FORM_ENDPOINT=${{ secrets.NEXT_PUBLIC_FORM_ENDPOINT }} >> ./.env.local
      - run: yarn download-schema
      - run: yarn generate-types
      - run: yarn tsc
      - run: yarn lint
      - run: yarn build
